name: "Run Rustfmt and Annotate"
description: |
  Run `cargo fmt` and check Rust code.
  Highlights places which are not correctly formatted via annotations.
  Fork of "Check formatting of Rust code with rustfmt".

branding:
  icon: "align-left"
  color: "yellow"

inputs:
  github_token:
    description: "Set to secrets.GITHUB_TOKEN"
    required: true
  manifest-path:
    description: "Specify the --manifest-path argument to rustfmt"
    required: false
    default: "./Cargo.toml"

runs:
  using: composite
  steps:

    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: jq curl
        version: 1.0

    - name: Run Rustfmt
      shell: bash
      run: cargo fmt --all --manifest-path=${{ inputs.manifest-path }} -- --color=never --emit=json > rustfmt-out.json

    - name: Create Annotations
      shell: bash
      run: |

        curl -sS --request GET \
          --url 'https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs' \
          --header 'authorization: Bearer ${{ inputs.github_token }}' \
          --header 'accept: application/vnd.github+json' \
          --output jobs.json

        CHECK_RUN_URL=$(jq -r '.jobs[] | select(.name == "${{ github.job }}") | .check_run_url' jobs.json)

        RUSTFMT_ERROR_COUNT=$(jq 'length' rustfmt-out.json)

        if [ $RUSTFMT_ERROR_COUNT -eq 0 ]; then
          echo "No formatting errors found."
          exit 0
        fi

        echo "Found $RUSTFMT_ERROR_COUNT formatting errors."

        jq -f '${{ github.action_path }}/rustfmt-to-annotations.jq' \
          --arg pwd "${PWD}/" \
          rustfmt-out.json > annotations.json

        curl -sS --request PATCH \
          --url "$CHECK_RUN_URL" \
          --header 'authorization: Bearer ${{ inputs.github_token }}' \
          --header 'content-type: application/json' \
          --header 'accept: application/vnd.github+json' \
          --data @'annotations.json' \
          --output /dev/null
        
        exit 1
